### ISSUE TITLE
update resource fails

### ISSUE THREAD

**Issue by mattbailey0** [ckan/ckanext-datastorer#42]
Attempting to update resource:
http://opendatadc.org/dataset/dc-211-resources

and it bonks on this file (at time of writing, the only one in the resource):
http://opendatadc.org/dataset/dc-211-resources/resource/81d74b9f-6793-469a-b47d-a097d8ca3a86

command:
`paster datastorer update dc-211-resources -c [path]/production.ini`

traceback:

```
013-05-21 22:33:32,674 INFO  [root] Header offset: 0.
2013-05-21 22:34:17,379 INFO  [root] Guessed types: [Integer, String, String, String, String, String, Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, Integer, String, Decimal, Decimal, String, String, String, String, String, Integer, String, String, String, String, String, String, Integer, String, String, String, String, String, String, String, String, String, String, Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, DateUtil, DateUtil, DateUtil, DateUtil, String, String, String, String, DateUtil, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String]
2013-05-21 22:34:17,379 INFO  [root] Deleting existing datastore (it may not exist): 81d74b9f-6793-469a-b47d-a097d8ca3a86.
2013-05-21 22:34:17,887 INFO  [root] Creating: 81d74b9f-6793-469a-b47d-a097d8ca3a86.
Traceback (most recent call last):
  File "[path]/pyenv/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "[path]/pyenv/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "[path]/pyenv/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "[path]/pyenv/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "[path]/pyenv/src/ckanext-datastorer/ckanext/datastorer/commands.py", line 129, in command
    tasks._datastorer_upload(context, resource, logger)
  File "[path]pyenv/src/ckanext-datastorer/ckanext/datastorer/tasks.py", line 177, in _datastorer_upload
    for data in chunky(row_set.dicts(), 100):
  File "[path]/pyenv/src/ckanext-datastorer/ckanext/datastorer/tasks.py", line 171, in chunky
    dict, itertools.islice(it, n)))
  File "[path]/pyenv/local/lib/python2.7/site-packages/messytables/core.py", line 198, in dicts
    for row in generator:
  File "[path]/pyenv/local/lib/python2.7/site-packages/messytables/core.py", line 179, in __iter__
    row = processor(self, row)
  File "[path]/pyenv/local/lib/python2.7/site-packages/messytables/types.py", line 196, in apply_types
    cell.value = type.cast(cell.value)
  File "[path]/pyenv/local/lib/python2.7/site-packages/messytables/types.py", line 73, in cast
    return locale.atoi(value)
  File "[path]/pyenv/lib/python2.7/locale.py", line 312, in atoi
    return atof(str, int)
  File "[path]/pyenv/lib/python2.7/locale.py", line 308, in atof
    return func(string)
ValueError: invalid literal for int() with base 10: '(888) 687-2277'
```

**Comment by domoritz** [comment]
At the moment the file is not available (I tried http://ec2-174-129-189-109.compute-1.amazonaws.com/storage/f/2013-05-12T14%3A50%3A58.063Z/211.csv). Have you got another file that also fails?

**Comment by mattbailey0** [comment]
Apologies; moved the server last night and did not have an elastic IP set up. 

http://ec2-54-235-58-226.compute-1.amazonaws.com/storage/f/2013-05-12T14%3A50%3A58.063Z/211.csv
